In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\users\sg21129\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [2]:
#Import the numpy package under the name np 
import numpy as np

In [3]:
#Print the numpy version and the configuration 
np.__version__

'1.21.3'

In [4]:
a=np.array([1,2,3,4,5])
print(a)
print(a.shape)

[1 2 3 4 5]
(5,)


In [6]:
#Create a null vector of size 10
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
# How to find the memory size of any array 
a=np.array([1,2,3,4,5])
print(a.size)
print(a.itemsize)

5
4


In [8]:
# How to get the documentation of the numpy add function from the command line?
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [10]:
# Create a null vector of size 10 but the fifth value which is 1 
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
# Create a vector with values ranging from 10 to 49 
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
 #Reverse a vector (first element becomes last) 
a=np.arange(9)
print(a[::-1])

[8 7 6 5 4 3 2 1 0]


In [18]:
#Create a 3x3 matrix with values ranging from 0 to 8
a=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
#Find indices of non-zero elements from [1,2,0,0,4,0] 


In [25]:
# Create a 3x3 identity matrix
a = np.eye(3) 
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Create a 3x3x3 array with random values 